spring:
  profiles:
    active: dev
  # 页面默认前缀目录
  #mvc:
   # view:
     # prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
     # suffix: .jsp
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 100MB
server:
  port: 8081
 #cache配置?
#  cache:
#    cache-names: generalCache
#    type: redis


renren:
  cluster: false  #集群配置  true集群环境   false单机环境，还需打开pom.xml里的spring-session-data-redis注释
  globalSessionTimeout: 3600   #单机环境，session过期时间为60分钟
  redis:
    open: false  #是否开启redis缓存  true开启   false关闭

uploadAbsolutePath: /mySource
logging:
  config: classpath:logback-spring.xml
  path: /logs
#此处和以上冲突与否 ,未知
logback:
  logdir: /logs
  appname: springbootEdu

#mybatis 配置
#mybatis:
#  dao-locations: classpath:resources/mappers/*.xml
#  config-location: classpath:mybatisConfig.xml
#  type-aliases-package: com.hpedu.web.core.*.pojo

# mybatisPlus 
mybatis-plus:
  mapper-locations: classpath:/mappers/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hpedu.web.core.*.pojo
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #表下划线
#      table-underline: false 
      #数据库 大写模式 
#      capital-mode: false
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
#刷新mapper 调试神器
#    refresh: true
      #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
  #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
#  原生配置?
  configuration:
#    驼峰
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    
    
    
#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

##  returnPageInfo: check

---




# 驱动配置信息
spring:
  profiles: dev
  datasource:
    druid:
      #监控统计拦截的filters
      filters: stat
      url: jdbc:mysql://localhost:3306/hpedu?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: javagd
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false




---



# 驱动配置信息
spring:
  profiles: prod
  datasource:
    druid:
      #监控统计拦截的filters
      filters: stat
      url: jdbc:mysql://localhost:3306/hpedu?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: javagd
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false





